development:
  adapter: postgresql
  encoding: utf8
  database: cornbread_muffins_development
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: cornbread_muffins_test
  host: localhost